/**
 * Base de données des 50 maisons d'édition françaises les plus influentes.
 * Données à titre indicatif — vérifiez toujours sur le site officiel de chaque éditeur.
 * Mis à jour : 2025
 */

export const PUBLISHERS = [
  /* ──────────────── PRESTIGE ★★★★★ ──────────────── */
  {
    id: "gallimard",
    nom: "Gallimard",
    groupe: "Groupe Gallimard",
    ville: "Paris",
    genres: ["Littérature générale", "Roman", "Poésie", "Théâtre", "Essai", "Biographie"],
    specialite: "Maison emblématique de la littérature française. 36 prix Nobel. Collection Blanche.",
    prestige: 5,
    voie: "courrier",
    contact: "5, rue Sébastien-Bottin — 75007 Paris",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "1 page",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 50,
      formatManuscrit: "Police lisible 12pt, interligne 1,5, marges standard, numéros de page",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "4 à 6 mois",
    conseil: "Ne jamais téléphoner ni relancer par email. Ne pas envoyer d'originaux. Joindre une enveloppe timbrée pour le retour.",
    noteExpert: "Le comité de lecture est très sélectif. Le premier roman est rarement accepté. Persévérance essentielle.",
  },
  {
    id: "seuil",
    nom: "Le Seuil",
    groupe: "Groupe Média-Participations",
    ville: "Paris",
    genres: ["Littérature française", "Roman", "Sciences humaines", "Histoire", "Jeunesse"],
    specialite: "Éditeur de référence pour la littérature et les sciences humaines. Collection Fiction & Cie.",
    prestige: 5,
    voie: "courrier",
    contact: "25, rue Jacob — 75006 Paris",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "1 à 2 pages",
      noteIntention: true,
      noteIntentionLongueur: "1 page",
      bio: true,
      extraits: true,
      extraitsNbPages: 50,
      formatManuscrit: "Tapuscrit standard, numéroté",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "3 à 6 mois",
    conseil: "Précisez dans la lettre la collection visée. Un refus du Seuil reste une distinction.",
    noteExpert: "Distingue bien littérature et documents. Mentionnez si votre ouvrage est un roman ou un essai.",
  },
  {
    id: "grasset",
    nom: "Grasset & Fasquelle",
    groupe: "Hachette Livre",
    ville: "Paris",
    genres: ["Littérature générale", "Roman", "Essai politique", "Biographie", "Documents"],
    specialite: "Maison fondée en 1907, tradition d'audace littéraire. Auteurs comme Proust, Malraux.",
    prestige: 5,
    voie: "courrier",
    contact: "61, rue des Saints-Pères — 75006 Paris",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "1 page",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 50,
      formatManuscrit: "Double interligne conseillé, police 12pt",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "2 à 4 mois",
    conseil: "Grasset apprécie les lettres courtes et percutantes. Évitez les comparaisons avec de grands auteurs.",
    noteExpert: "Comité de lecture actif. Accueillant pour les premiers romans de qualité.",
  },
  {
    id: "actes-sud",
    nom: "Actes Sud",
    groupe: "Actes Sud (indépendant)",
    ville: "Arles",
    genres: ["Littérature étrangère", "Littérature française", "Policier", "Jeunesse", "Arts", "Nature"],
    specialite: "Maison indépendante de référence. Traduit 40 langues. Engagement éditorial fort.",
    prestige: 5,
    voie: "courrier",
    contact: "Le Méjan — Place Nina-Berberova — 13200 Arles",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "1 à 2 pages",
      noteIntention: true,
      noteIntentionLongueur: "1 page",
      bio: true,
      extraits: true,
      extraitsNbPages: 50,
      formatManuscrit: "Manuscrit complet ou 50 premières pages, police lisible, numéroté",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "3 à 5 mois",
    conseil: "Actes Sud valorise les projets à forte singularité. Expliquez ce que votre livre apporte d'unique.",
    noteExpert: "Particulièrement réceptif aux voix originales et aux univers construits. Fort en nature writing.",
  },
  {
    id: "pol",
    nom: "P.O.L",
    groupe: "Groupe Gallimard",
    ville: "Paris",
    genres: ["Littérature expérimentale", "Roman", "Poésie", "Essai", "Théâtre"],
    specialite: "Éditeur de l'exigence littéraire et de l'expérimentation formelle. Auteurs : Houellebecq, Echenoz.",
    prestige: 5,
    voie: "courrier",
    contact: "33, rue Saint-André-des-Arts — 75006 Paris",
    exigences: {
      lettre: true,
      synopsis: false,
      noteIntention: true,
      noteIntentionLongueur: "libre",
      bio: true,
      extraits: true,
      extraitsNbPages: 30,
      formatManuscrit: "Aucun format imposé — P.O.L apprécie les manuscrits sous leur forme naturelle",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "4 à 8 mois",
    conseil: "P.O.L n'est pas attaché aux conventions. La note d'intention doit refléter votre véritable démarche créative.",
    noteExpert: "Ne pas envoyer de synopsis traditionnel. Préférez une lettre qui parle de votre rapport à l'écriture.",
  },
  {
    id: "minuit",
    nom: "Les Éditions de Minuit",
    groupe: "Indépendant",
    ville: "Paris",
    genres: ["Littérature française", "Roman", "Essai"],
    specialite: "Éditeur de la Résistance, du Nouveau Roman. Auteurs : Beckett, Duras, Simon, Echenoz.",
    prestige: 5,
    voie: "courrier",
    contact: "7, rue Bernard-Palissy — 75006 Paris",
    exigences: {
      lettre: true,
      synopsis: false,
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 30,
      formatManuscrit: "Tapuscrit soigné, numéroté",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "6 mois à 1 an",
    conseil: "Très sélectif. N'envoyez votre manuscrit que si vous avez lu et aimé plusieurs ouvrages du catalogue.",
    noteExpert: "Publier à Minuit est exceptionnel. Le catalogue est cohérent et intentionnel depuis 80 ans.",
  },

  /* ──────────────── PRESTIGE ★★★★ ──────────────── */
  {
    id: "flammarion",
    nom: "Flammarion",
    groupe: "Groupe Madrigall (Gallimard)",
    ville: "Paris",
    genres: ["Littérature", "Roman", "Histoire", "Jeunesse", "Beaux-Arts", "Sciences"],
    specialite: "Maison généraliste de premier plan. Catalogue très large, du roman grand public au livre d'art.",
    prestige: 4,
    voie: "agent",
    contact: "Via agent littéraire recommandé — 87, quai Panhard-et-Levassor 75013 Paris",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "1 à 2 pages",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 50,
      formatManuscrit: "Standard, numéroté",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "3 à 6 mois",
    conseil: "Flammarion travaille principalement avec des agents. Un agent augmente significativement vos chances.",
    noteExpert: "Soumissions directes possibles mais moins efficaces. Investissez d'abord dans la recherche d'un agent.",
  },
  {
    id: "albin-michel",
    nom: "Albin Michel",
    groupe: "Albin Michel (indépendant)",
    ville: "Paris",
    genres: ["Littérature générale", "Roman", "Humour", "Spiritualité", "Jeunesse", "BD"],
    specialite: "Grand éditeur indépendant, fort en romans populaires et spiritualité. Auteurs : Werber, Lévy.",
    prestige: 4,
    voie: "courrier",
    contact: "22, rue Huyghens — 75014 Paris",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "2 pages",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 50,
      formatManuscrit: "Police Times ou Garamond 12pt, double interligne, pages numérotées",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "3 à 6 mois",
    conseil: "Albin Michel apprécie les romans avec une forte identité commerciale. Mentionnez le public cible.",
    noteExpert: "Comité de lecture très actif. Fort en bestsellers. Moins intéressé par la littérature expérimentale.",
  },
  {
    id: "fayard",
    nom: "Fayard",
    groupe: "Hachette Livre",
    ville: "Paris",
    genres: ["Littérature", "Histoire", "Biographie", "Essai politique", "Roman policier"],
    specialite: "Maison de tradition, forte en histoire et biographies. Collection Le Livre de Poche.",
    prestige: 4,
    voie: "courrier",
    contact: "75, rue des Saints-Pères — 75006 Paris",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "1 à 2 pages",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 50,
      formatManuscrit: "Standard, police 12pt, pages numérotées",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "3 à 5 mois",
    conseil: "Fayard est particulièrement intéressé par les sujets historiques bien documentés.",
    noteExpert: "Si votre roman a une forte dimension historique, mentionnez vos sources et votre recherche.",
  },
  {
    id: "stock",
    nom: "Stock",
    groupe: "Hachette Livre",
    ville: "Paris",
    genres: ["Littérature française", "Roman", "Essai", "Document"],
    specialite: "Maison de tradition littéraire, ouverte aux nouvelles voix. Collection La Bleue.",
    prestige: 4,
    voie: "courrier",
    contact: "21, rue du Montparnasse — 75006 Paris",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "1 à 2 pages",
      noteIntention: true,
      noteIntentionLongueur: "1 page",
      bio: true,
      extraits: true,
      extraitsNbPages: 50,
      formatManuscrit: "Tapuscrit numéroté, police lisible 12pt",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "3 à 5 mois",
    conseil: "Stock valorise les projets qui ont une cohérence entre le fond et la forme.",
    noteExpert: "Accueillant pour les premiers romans exigeants et bien écrits.",
  },
  {
    id: "robert-laffont",
    nom: "Robert Laffont",
    groupe: "Groupe Editis",
    ville: "Paris",
    genres: ["Roman", "Documents", "Biographie", "Histoire", "Témoignage", "Thriller"],
    specialite: "Maison de grand public. Fort en romans populaires et documents de société.",
    prestige: 4,
    voie: "courrier",
    contact: "24, avenue Marceau — 75008 Paris",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "2 pages",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 50,
      formatManuscrit: "Police standard 12pt, double interligne, pages numérotées",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "3 à 6 mois",
    conseil: "Pensez à préciser le potentiel commercial et le public cible de votre projet.",
    noteExpert: "Robert Laffont est sensible aux histoires universelles et aux arcs émotionnels forts.",
  },
  {
    id: "mercure-de-france",
    nom: "Mercure de France",
    groupe: "Groupe Gallimard",
    ville: "Paris",
    genres: ["Littérature française", "Essai", "Poésie", "Roman classique"],
    specialite: "L'une des plus anciennes maisons françaises (1672). Catalogue littéraire et patrimonial.",
    prestige: 4,
    voie: "courrier",
    contact: "26, rue de Condé — 75006 Paris",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "1 page",
      noteIntention: true,
      noteIntentionLongueur: "1 page",
      bio: true,
      extraits: true,
      extraitsNbPages: 30,
      formatManuscrit: "Standard, lisible",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "4 à 6 mois",
    conseil: "Mercure de France cherche des voix singulières inscrites dans une tradition littéraire.",
    noteExpert: "Convient aux romans littéraires exigeants qui ne sacrifient pas la lisibilité.",
  },
  {
    id: "christian-bourgois",
    nom: "Christian Bourgois",
    groupe: "Groupe Editis",
    ville: "Paris",
    genres: ["Littérature étrangère", "SF", "Fantasy", "Roman expérimental"],
    specialite: "L'éditeur qui a publié Tolkien et Burroughs en France. Spécialiste de l'imaginaire et de l'avant-garde.",
    prestige: 4,
    voie: "courrier",
    contact: "8, rue du Cherche-Midi — 75006 Paris",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "1 à 2 pages",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 50,
      formatManuscrit: "Standard",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "3 à 5 mois",
    conseil: "Idéal pour la SF et le fantastique littéraire. Mentionnez vos influences.",
    noteExpert: "Publie peu de français en SF. Très ouvert à l'expérimentation formelle.",
  },
  {
    id: "sabine-wespieser",
    nom: "Sabine Wespieser",
    groupe: "Indépendant",
    ville: "Paris",
    genres: ["Littérature française", "Littérature étrangère", "Roman"],
    specialite: "Petite maison indépendante exigeante. Catalogue soigné, voix singulières.",
    prestige: 4,
    voie: "email",
    contact: "sw@wespieser.com",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "1 page",
      noteIntention: true,
      noteIntentionLongueur: "1 page",
      bio: true,
      extraits: true,
      extraitsNbPages: 30,
      formatManuscrit: "Fichier .doc ou .docx, police Times 12pt, interligne 1,5",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "2 à 4 mois",
    conseil: "Envoyez un email avec les documents en pièces jointes. Soyez concis et précis.",
    noteExpert: "Réponse plus rapide qu'en courrier. Maison à taille humaine, relation directe avec l'éditrice.",
  },
  {
    id: "zulma",
    nom: "Zulma",
    groupe: "Indépendant",
    ville: "Paris",
    genres: ["Littérature mondiale", "Littérature française", "Roman", "Nouvelles"],
    specialite: "Éditeur de la diversité littéraire mondiale. Fort en littératures africaines, asiatiques, latino.",
    prestige: 4,
    voie: "portail",
    contact: "zulma.fr/contact — rubrique \"Envoyer un manuscrit\"",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "1 à 2 pages",
      noteIntention: true,
      noteIntentionLongueur: "1 page",
      bio: true,
      extraits: true,
      extraitsNbPages: 30,
      formatManuscrit: "Fichier PDF ou Word, via le portail en ligne",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "3 à 5 mois",
    conseil: "Précisez la dimension internationale ou multiculturelle de votre projet si elle existe.",
    noteExpert: "Zulma est sensible aux voix littéraires qui traversent les frontières culturelles.",
  },
  {
    id: "lolivier",
    nom: "L'Olivier",
    groupe: "Groupe Le Seuil",
    ville: "Paris",
    genres: ["Littérature française et étrangère", "Roman", "Essai littéraire"],
    specialite: "Collection de littérature exigeante du Seuil. Auteurs : Philippe Djian, Rick Moody.",
    prestige: 4,
    voie: "courrier",
    contact: "25, rue Jacob — 75006 Paris (à l'attention de L'Olivier)",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "1 page",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 50,
      formatManuscrit: "Standard, numéroté",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "3 à 6 mois",
    conseil: "Précisez dans la lettre que vous soumettez à L'Olivier spécifiquement.",
    noteExpert: "Catalogue très cohérent. Lisez plusieurs titres avant de soumettre.",
  },
  {
    id: "verdier",
    nom: "Éditions Verdier",
    groupe: "Indépendant",
    ville: "Lagrasse (Aude)",
    genres: ["Littérature", "Poésie", "Sciences humaines", "Traduction"],
    specialite: "Éditeur indépendant du Sud de la France. Catalogue littéraire et philosophique de haute tenue.",
    prestige: 4,
    voie: "courrier",
    contact: "Route de Douzens — 11220 Lagrasse",
    exigences: {
      lettre: true,
      synopsis: false,
      noteIntention: true,
      noteIntentionLongueur: "libre",
      bio: true,
      extraits: true,
      extraitsNbPages: 30,
      formatManuscrit: "Standard",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "4 à 6 mois",
    conseil: "Verdier préfère les projets littéraires à forte identité formelle ou philosophique.",
    noteExpert: "Maison à l'éthique éditoriale forte. Relation durable avec ses auteurs.",
  },
  {
    id: "ecole-des-loisirs",
    nom: "L'École des Loisirs",
    groupe: "Indépendant",
    ville: "Paris",
    genres: ["Jeunesse (0-14 ans)", "Albums", "Roman jeunesse", "Roman ados"],
    specialite: "Référence en littérature jeunesse française. Auteurs : Pennac, Morgenstern.",
    prestige: 4,
    voie: "courrier",
    contact: "11, rue de Sèvres — 75006 Paris",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "1 page",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 30,
      formatManuscrit: "Police 12pt, interligne 1,5",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "3 à 6 mois",
    conseil: "Précisez la tranche d'âge cible. La collection (Mouche, Neuf, Médium…) est importante.",
    noteExpert: "Très sélectif. Lisez leur catalogue récent pour cerner leurs attentes.",
  },
  {
    id: "gallimard-jeunesse",
    nom: "Gallimard Jeunesse",
    groupe: "Groupe Gallimard",
    ville: "Paris",
    genres: ["Jeunesse (tous âges)", "Roman ados", "Albums", "Fantasy jeunesse"],
    specialite: "La plus grande maison de jeunesse française. Collections Folio Junior, Scripto, Giboulées.",
    prestige: 4,
    voie: "courrier",
    contact: "5, rue Sébastien-Bottin — 75007 Paris (Gallimard Jeunesse)",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "1 à 2 pages",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 50,
      formatManuscrit: "Standard, numéroté",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "4 à 6 mois",
    conseil: "Mentionnez impérativement la collection visée et la tranche d'âge cible.",
    noteExpert: "Comité de lecture dédié pour la jeunesse. Ne pas confondre avec Gallimard littérature.",
  },

  /* ──────────────── PRESTIGE ★★★ ──────────────── */
  {
    id: "plon",
    nom: "Plon",
    groupe: "Groupe Editis",
    ville: "Paris",
    genres: ["Histoire", "Biographie", "Roman historique", "Mémoires", "Document"],
    specialite: "Maison de l'histoire et de la grande biographie. Auteurs : de Gaulle, Malraux.",
    prestige: 3,
    voie: "courrier",
    contact: "76, rue Bonaparte — 75006 Paris",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "2 pages",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 50,
      formatManuscrit: "Police Times 12pt, double interligne, numéroté",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "2 à 4 mois",
    conseil: "Si votre roman est historique, mettez en avant la précision documentaire.",
    noteExpert: "Apprécie les romans de saga familiale ou les récits de mémoire.",
  },
  {
    id: "jc-lattes",
    nom: "JC Lattès",
    groupe: "Hachette Livre",
    ville: "Paris",
    genres: ["Roman contemporain", "Thriller", "Documents", "Témoignage", "Biographie"],
    specialite: "Maison grand public de Hachette. Fort en romans populaires et thrillers. Auteur : Joël Dicker.",
    prestige: 4,
    voie: "courrier",
    contact: "17, rue Jacob — 75006 Paris",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "2 pages",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 50,
      formatManuscrit: "Police standard 12pt, numéroté",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "2 à 4 mois",
    conseil: "JC Lattès cherche des romans avec un fort potentiel de diffusion. Mentionnez les comparaisons de marché.",
    noteExpert: "Particulièrement fort pour les thrillers et romans à grande échelle narrative.",
  },
  {
    id: "heloise-dormesson",
    nom: "Héloïse d'Ormesson",
    groupe: "Indépendant",
    ville: "Paris",
    genres: ["Roman", "Littérature étrangère", "Essai"],
    specialite: "Maison indépendante et familiale. Catalogue exigeant mais accessible. Lectures rapides.",
    prestige: 3,
    voie: "email",
    contact: "manuscrits@editions-ho.com",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "1 à 2 pages",
      noteIntention: true,
      noteIntentionLongueur: "1 page",
      bio: true,
      extraits: true,
      extraitsNbPages: 30,
      formatManuscrit: "Fichier Word ou PDF en pièce jointe",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "2 à 4 mois",
    conseil: "Envoyez par email avec les documents joints. Réponse plus rapide que la moyenne.",
    noteExpert: "Maison à taille humaine. Relation directe et humaine avec les auteurs.",
  },
  {
    id: "philippe-rey",
    nom: "Philippe Rey",
    groupe: "Indépendant",
    ville: "Paris",
    genres: ["Littérature française", "Littérature étrangère", "Sciences humaines", "Essai"],
    specialite: "Maison indépendante au catalogue exigeant. Traduit beaucoup d'auteurs étrangers.",
    prestige: 3,
    voie: "email",
    contact: "editions@philippe-rey.fr",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "1 page",
      noteIntention: true,
      noteIntentionLongueur: "1 page",
      bio: true,
      extraits: true,
      extraitsNbPages: 30,
      formatManuscrit: "Fichier Word ou PDF",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "2 à 4 mois",
    conseil: "Précisez si votre projet a été traduit ou non, et votre rapport aux littératures étrangères.",
    noteExpert: "Ouvert aux voix singulières. Petit catalogue, grande attention portée à chaque titre.",
  },
  {
    id: "rivages",
    nom: "Rivages",
    groupe: "Groupe Payot & Rivages",
    ville: "Paris",
    genres: ["Roman noir", "Thriller", "Polar", "Littérature étrangère"],
    specialite: "Référence française du roman noir. Collections Rivages/noir, Rivages/thriller.",
    prestige: 3,
    voie: "courrier",
    contact: "9, rue du Cherche-Midi — 75006 Paris",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "2 pages",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 50,
      formatManuscrit: "Standard",
      longueurMin: 60000,
      longueurMax: null,
    },
    delaiReponse: "3 à 5 mois",
    conseil: "Expliquez clairement le sous-genre (noir, thriller, cozy, policier classique…). Respectez les codes.",
    noteExpert: "Fort en roman noir américain traduit. Les auteurs français y sont accueillis dans Rivages/noir.",
  },
  {
    id: "belfond",
    nom: "Belfond",
    groupe: "Groupe Editis (Place des Éditeurs)",
    ville: "Paris",
    genres: ["Roman", "Littérature étrangère", "Thriller", "Biographie"],
    specialite: "Maison de roman grand public. Spécialiste de la fiction internationale.",
    prestige: 3,
    voie: "courrier",
    contact: "12, avenue d'Iéna — 75116 Paris",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "2 pages",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 50,
      formatManuscrit: "Police Times 12pt, double interligne",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "2 à 4 mois",
    conseil: "Belfond cherche des romans avec une forte intrigue et un rythme soutenu.",
    noteExpert: "Particulièrement ouvert à la fiction contemporaine de qualité avec dimension internationale.",
  },
  {
    id: "calmann-levy",
    nom: "Calmann-Lévy",
    groupe: "Hachette Livre",
    ville: "Paris",
    genres: ["Roman", "Thriller", "Histoire", "Sciences humaines", "Fantasy"],
    specialite: "Maison polyvalente historique, forte en romans populaires et thrillers français.",
    prestige: 3,
    voie: "courrier",
    contact: "21, rue du Montparnasse — 75006 Paris",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "2 pages",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 50,
      formatManuscrit: "Standard, police 12pt, numéroté",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "2 à 4 mois",
    conseil: "Indiquez clairement le genre et le positionnement de votre roman.",
    noteExpert: "Propose la collection Calmann-Lévy Noir pour les thrillers et polars.",
  },
  {
    id: "anne-carriere",
    nom: "Anne Carrière",
    groupe: "Albin Michel",
    ville: "Paris",
    genres: ["Roman", "Humour", "Témoignage", "Littérature générale"],
    specialite: "Maison de l'humour et du roman populaire. Édite Riad Sattouf, Muriel Barbery.",
    prestige: 3,
    voie: "email",
    contact: "anne-carriere@editions-ac.com",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "1 à 2 pages",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 30,
      formatManuscrit: "Fichier Word ou PDF",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "2 à 3 mois",
    conseil: "Si votre texte a une dimension humoristique, mentionnez-le et donnez des exemples.",
    noteExpert: "Maison dynamique. Bon tremplin pour les romans populaires de qualité.",
  },
  {
    id: "michel-lafon",
    nom: "Michel Lafon",
    groupe: "Indépendant",
    ville: "Neuilly-sur-Seine",
    genres: ["Roman", "Biographie", "Témoignage", "Développement personnel", "Thriller"],
    specialite: "Spécialiste des bestsellers et biographies de célébrités. Fort en vente grand public.",
    prestige: 3,
    voie: "courrier",
    contact: "7-13, boulevard Paul-Émile-Victor — 92200 Neuilly-sur-Seine",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "2 pages",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 50,
      formatManuscrit: "Police Times 12pt, double interligne",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "2 à 3 mois",
    conseil: "Précisez le potentiel commercial et les concurrences directes sur le marché.",
    noteExpert: "Idéal pour les romans grand public à fort potentiel commercial ou les biographies de personnalités.",
  },
  {
    id: "xo-editions",
    nom: "XO Éditions",
    groupe: "Indépendant",
    ville: "Paris",
    genres: ["Thriller", "Polar", "Roman populaire", "Biographie"],
    specialite: "Spécialiste du thriller français. Auteurs : Bernard Minier, Maxime Chattam.",
    prestige: 3,
    voie: "email",
    contact: "manuscrits@xo-editions.com",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "2 à 3 pages",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 50,
      formatManuscrit: "Fichier Word, police Times 12pt, double interligne",
      longueurMin: 80000,
      longueurMax: null,
    },
    delaiReponse: "2 à 4 mois",
    conseil: "Pour un thriller, développez précisément le mécanisme de tension et les rebondissements clés.",
    noteExpert: "XO est LA maison du thriller français. Un manuscrit de genre doit être irréprochable.",
  },
  {
    id: "les-arenes",
    nom: "Les Arènes",
    groupe: "Indépendant",
    ville: "Paris",
    genres: ["Document", "Société", "Témoignage", "Investigation", "Roman"],
    specialite: "Éditeur engagé, fort en livres de société et témoignages. Auteurs : Marion Cotillard, Edwy Plenel.",
    prestige: 3,
    voie: "email",
    contact: "contact@lesarenes.com",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "1 à 2 pages",
      noteIntention: true,
      noteIntentionLongueur: "1 page",
      bio: true,
      extraits: false,
      formatManuscrit: "Fichier Word ou PDF",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "2 à 3 mois",
    conseil: "Expliquez clairement l'enjeu de société de votre projet et pourquoi il est urgent.",
    noteExpert: "Les Arènes cherche des projets au positionnement clair et à l'impact social visible.",
  },
  {
    id: "denoel",
    nom: "Denoël",
    groupe: "Groupe Gallimard",
    ville: "Paris",
    genres: ["Science-Fiction", "Fantasy", "Thriller", "Littérature générale"],
    specialite: "Maison pionnière de la SF en France. Collections Présence du Futur, Sueurs Froides.",
    prestige: 3,
    voie: "courrier",
    contact: "9, rue du Cherche-Midi — 75006 Paris",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "2 pages",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 50,
      formatManuscrit: "Standard, numéroté",
      longueurMin: 60000,
      longueurMax: null,
    },
    delaiReponse: "3 à 5 mois",
    conseil: "Pour la SF, précisez bien la nature du sens of wonder et les grandes idées portées par votre récit.",
    noteExpert: "Denoël cherche de la SF littéraire, pas seulement du divertissement.",
  },
  {
    id: "buchet-chastel",
    nom: "Buchet-Chastel",
    groupe: "Indépendant",
    ville: "Paris",
    genres: ["Littérature française", "Musique", "Essai", "Roman"],
    specialite: "Maison indépendante exigeante. Fort en musique et en littérature de qualité.",
    prestige: 3,
    voie: "email",
    contact: "contact@buchetchastel.fr",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "1 à 2 pages",
      noteIntention: true,
      noteIntentionLongueur: "1 page",
      bio: true,
      extraits: true,
      extraitsNbPages: 30,
      formatManuscrit: "Fichier Word ou PDF",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "2 à 4 mois",
    conseil: "Si votre roman a une dimension musicale, c'est un atout. Mentionnez-le.",
    noteExpert: "Maison à taille humaine, très attentive à la qualité d'écriture.",
  },
  {
    id: "bragelonne",
    nom: "Bragelonne",
    groupe: "Indépendant",
    ville: "Paris",
    genres: ["Fantasy", "SF", "Thriller", "Horreur", "Romance fantastique"],
    specialite: "Premier éditeur français de fantasy et SF. Publie Tolkien, Pratchett, et de nombreux auteurs français.",
    prestige: 3,
    voie: "portail",
    contact: "bragelonne.fr — section Soumettre un manuscrit",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "2 pages",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 50,
      formatManuscrit: "Via le formulaire en ligne, fichier .doc ou .docx",
      longueurMin: 80000,
      longueurMax: null,
    },
    delaiReponse: "3 à 6 mois",
    conseil: "Précisez avec soin le sous-genre (fantasy épique, urban fantasy, SF hard, space opera…).",
    noteExpert: "Bragelonne privilégie les récits avec un univers construit et cohérent.",
  },
  {
    id: "latalante",
    nom: "L'Atalante",
    groupe: "Indépendant",
    ville: "Lyon",
    genres: ["Science-Fiction", "Fantasy", "SFFF", "Imaginaire"],
    specialite: "Éditeur lyonnais indépendant de référence en SFFF. Qualité éditoriale reconnue.",
    prestige: 3,
    voie: "email",
    contact: "manuscrits@latalante.com",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "2 pages",
      noteIntention: true,
      noteIntentionLongueur: "1 page",
      bio: true,
      extraits: true,
      extraitsNbPages: 50,
      formatManuscrit: "Fichier Word, police 12pt, interligne 1,5",
      longueurMin: 70000,
      longueurMax: null,
    },
    delaiReponse: "3 à 6 mois",
    conseil: "L'Atalante valorise l'originalité et la cohérence de l'univers. Évitez les clones.",
    noteExpert: "Maison très appréciée des auteurs. Accompagnement éditorial de qualité.",
  },
  {
    id: "fleuve-editions",
    nom: "Fleuve Éditions",
    groupe: "Groupe Editis",
    ville: "Paris",
    genres: ["Thriller", "Polar", "Roman policier", "Horreur"],
    specialite: "Spécialiste du thriller et du polar français. Auteur : Fred Vargas.",
    prestige: 3,
    voie: "courrier",
    contact: "24, avenue Marceau — 75008 Paris",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "2 à 3 pages",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 50,
      formatManuscrit: "Police Times 12pt, double interligne, numéroté",
      longueurMin: 80000,
      longueurMax: null,
    },
    delaiReponse: "2 à 4 mois",
    conseil: "Mettez en avant la mécanique du suspense, les personnages récurrents éventuels, et le rythme.",
    noteExpert: "Intéressé par les séries policières avec personnage fort. Pensez à une suite possible.",
  },
  {
    id: "pygmalion",
    nom: "Pygmalion",
    groupe: "Groupe Flammarion",
    ville: "Paris",
    genres: ["Histoire", "Ésotérisme", "Spiritualité", "Roman historique", "Biographie"],
    specialite: "Maison spécialisée en histoire, ésotérisme et romans historiques.",
    prestige: 3,
    voie: "courrier",
    contact: "87, quai Panhard-et-Levassor — 75647 Paris cedex 13",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "2 pages",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 50,
      formatManuscrit: "Standard",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "2 à 4 mois",
    conseil: "Si votre roman est historique ou ésotérique, précisez vos sources et votre expertise.",
    noteExpert: "Bien positionné pour les romans à clés ésotériques ou historiques documentés.",
  },
  {
    id: "manufacture-de-livres",
    nom: "La Manufacture de livres",
    groupe: "Indépendant",
    ville: "Paris",
    genres: ["Thriller", "Polar", "Roman noir"],
    specialite: "Maison indépendante dédiée au polar et thriller français. Auteur : Franck Thilliez.",
    prestige: 3,
    voie: "email",
    contact: "contact@lamanufacturedelivres.fr",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "2 à 3 pages",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 50,
      formatManuscrit: "Fichier Word ou PDF",
      longueurMin: 80000,
      longueurMax: null,
    },
    delaiReponse: "2 à 4 mois",
    conseil: "Maison spécialisée : ne soumettez que des thrillers ou polars. La qualité d'écriture prime.",
    noteExpert: "Très bon tremplin pour le thriller français. Suivi éditorial rigoureux.",
  },
  {
    id: "syros",
    nom: "Syros",
    groupe: "Groupe Editis",
    ville: "Paris",
    genres: ["Roman jeunesse", "Roman ados", "Société", "Fantastique jeunesse"],
    specialite: "Fort en romans jeunesse engagés et en fantasy pour adolescents.",
    prestige: 3,
    voie: "email",
    contact: "synopsyros@syros.fr",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "1 à 2 pages",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 30,
      formatManuscrit: "Fichier Word ou PDF",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "2 à 4 mois",
    conseil: "Précisez impérativement la tranche d'âge et la collection visée (Mini Syros, Roman+, etc.).",
    noteExpert: "Engagé socialement. Apprécie les romans qui parlent aux ados d'aujourd'hui.",
  },
  {
    id: "hachette-romans",
    nom: "Hachette Romans",
    groupe: "Hachette Livre",
    ville: "Paris",
    genres: ["Roman contemporain", "Chick-lit", "Romance", "Feel-good", "Thriller doux"],
    specialite: "Maison de roman grand public et feel-good. Fort en success stories populaires.",
    prestige: 3,
    voie: "email",
    contact: "hachette-romans@hachette-livre.fr",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "2 pages",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 30,
      formatManuscrit: "Fichier Word",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "2 à 3 mois",
    conseil: "Positionnez clairement votre roman dans le marché. Mentionnez vos comparables.",
    noteExpert: "Bon accueil pour les romans feel-good, comédies romantiques et récits contemporains.",
  },
  {
    id: "presses-de-la-cite",
    nom: "Presses de la Cité",
    groupe: "Groupe Editis",
    ville: "Paris",
    genres: ["Roman terroir", "Roman régional", "Thriller", "Roman populaire"],
    specialite: "Spécialiste du roman du terroir et du roman populaire régional. Très fort en vente grande surface.",
    prestige: 3,
    voie: "courrier",
    contact: "12, avenue d'Iéna — 75116 Paris",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "2 pages",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 50,
      formatManuscrit: "Police Times 12pt, double interligne",
      longueurMin: 80000,
      longueurMax: null,
    },
    delaiReponse: "2 à 4 mois",
    conseil: "Précisez la région ou le terroir concerné. La dimension locale est un atout.",
    noteExpert: "Idéal pour les romans de terroir ou saga familiale ancrée dans une région française.",
  },
  {
    id: "les-escales",
    nom: "Les Escales",
    groupe: "Groupe Editis",
    ville: "Paris",
    genres: ["Roman", "Biographie", "Littérature étrangère", "Document"],
    specialite: "Maison de voyage littéraire et biographies. Catalogue éclectique et ouvert.",
    prestige: 3,
    voie: "email",
    contact: "manuscrits@les-escales.com",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "1 à 2 pages",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 30,
      formatManuscrit: "Fichier Word ou PDF",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "2 à 3 mois",
    conseil: "Si votre roman a une dimension voyage ou géographique marquée, mettez-la en avant.",
    noteExpert: "Maison ouverte et accessible pour les premiers romans de qualité.",
  },
  {
    id: "casterman",
    nom: "Casterman",
    groupe: "Flammarion",
    ville: "Paris / Bruxelles",
    genres: ["BD", "Roman graphique", "Roman jeunesse", "Roman ados", "Science-Fiction"],
    specialite: "Maison historique de la BD franco-belge (Tintin). Collections romans pour jeunes et adultes.",
    prestige: 3,
    voie: "portail",
    contact: "casterman.com — rubrique \"Proposer un projet\"",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "1 à 2 pages",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 30,
      formatManuscrit: "Via le formulaire en ligne",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "3 à 5 mois",
    conseil: "Précisez si c'est un roman ou un projet BD. La cible (enfants/ados/adultes) est cruciale.",
    noteExpert: "Casterman Jeunesse et Casterman Romans sont deux comités différents.",
  },
  {
    id: "albin-michel-jeunesse",
    nom: "Albin Michel Jeunesse",
    groupe: "Albin Michel",
    ville: "Paris",
    genres: ["Jeunesse (0-15 ans)", "Albums", "Roman jeunesse", "Fantasy jeunesse"],
    specialite: "Forte position en jeunesse. Auteurs : Anna Todd (ado), Léa Silhol.",
    prestige: 3,
    voie: "courrier",
    contact: "22, rue Huyghens — 75014 Paris (Albin Michel Jeunesse)",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "1 page",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 30,
      formatManuscrit: "Standard",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "3 à 5 mois",
    conseil: "Indiquez la tranche d'âge précise et la collection visée.",
    noteExpert: "Comité jeunesse distinct d'Albin Michel adulte.",
  },
  {
    id: "la-table-ronde",
    nom: "La Table Ronde",
    groupe: "Groupe Gallimard",
    ville: "Paris",
    genres: ["Littérature générale", "Roman", "Histoire", "Essai", "Spiritualité"],
    specialite: "Maison de tradition littéraire et spirituelle. Auteurs : Julien Green, Marguerite Yourcenar.",
    prestige: 3,
    voie: "courrier",
    contact: "7, rue Corneille — 75006 Paris",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "1 à 2 pages",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 30,
      formatManuscrit: "Standard",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "3 à 5 mois",
    conseil: "La Table Ronde apprécie les projets avec une dimension spirituelle ou humaniste.",
    noteExpert: "Catalogue cohérent. Lisez quelques titres pour saisir leur ligne éditoriale.",
  },
  {
    id: "liana-levi",
    nom: "Liana Levi",
    groupe: "Indépendant",
    ville: "Paris",
    genres: ["Littérature étrangère", "Littérature française", "Roman", "Essai"],
    specialite: "Maison indépendante exigeante, spécialiste de la littérature italienne et méditerranéenne.",
    prestige: 3,
    voie: "courrier",
    contact: "8, rue Sébastien-Bottin — 75007 Paris",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "1 à 2 pages",
      noteIntention: true,
      noteIntentionLongueur: "1 page",
      bio: true,
      extraits: true,
      extraitsNbPages: 30,
      formatManuscrit: "Standard",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "3 à 5 mois",
    conseil: "Liana Levi est très ouvert aux littératures méditerranéennes et aux voix singulières.",
    noteExpert: "Maison confidentielle mais très respectée dans le milieu littéraire.",
  },

  /* ──────────────── PRESTIGE ★★ ──────────────── */
  {
    id: "city-editions",
    nom: "City Éditions",
    groupe: "Indépendant",
    ville: "Paris",
    genres: ["Romance", "Feel-good", "Thriller romantique", "Comédie"],
    specialite: "Spécialiste de la romance et du feel-good en France. Catalogue très commercial.",
    prestige: 2,
    voie: "email",
    contact: "contact@city-editions.com",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "2 à 3 pages",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 50,
      formatManuscrit: "Fichier Word, police 12pt, interligne 1,5",
      longueurMin: 60000,
      longueurMax: 120000,
    },
    delaiReponse: "1 à 3 mois",
    conseil: "Pour la romance, précisez les tropes, le niveau de sensualité, et le HEA/HFN.",
    noteExpert: "City publie beaucoup. Bon pour une première publication grand public. Contrats à surveiller.",
  },
  {
    id: "milady",
    nom: "Milady",
    groupe: "Indépendant (Bragelonne)",
    ville: "Paris",
    genres: ["Romance", "Romance fantastique", "Fantasy romantique", "New Adult", "SF romance"],
    specialite: "Filiale de Bragelonne dédiée à la romance et au fantastique romantique.",
    prestige: 2,
    voie: "portail",
    contact: "bragelonne.fr — section Milady Soumettre un manuscrit",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "2 à 3 pages",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 50,
      formatManuscrit: "Via le formulaire, fichier .doc ou .docx",
      longueurMin: 70000,
      longueurMax: null,
    },
    delaiReponse: "2 à 4 mois",
    conseil: "Précisez le sous-genre de romance et les éléments fantastiques s'il y en a.",
    noteExpert: "Milady a une communauté de lectrices très fidèle. Important pour le marketing.",
  },
  {
    id: "nathan",
    nom: "Nathan",
    groupe: "Groupe Editis",
    ville: "Paris",
    genres: ["Jeunesse", "Éducatif", "Roman ados", "Documentaire jeunesse"],
    specialite: "Maison scolaire et parascolaire, mais aussi forte en romans jeunesse et ados.",
    prestige: 3,
    voie: "email",
    contact: "litterature@nathan.fr",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "1 à 2 pages",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 30,
      formatManuscrit: "Fichier Word ou PDF",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "3 à 5 mois",
    conseil: "Précisez la tranche d'âge et si le texte s'inscrit dans un projet pédagogique.",
    noteExpert: "Nathan Poche est une filiale réservée aux auteurs déjà publiés.",
  },
  {
    id: "slatkine",
    nom: "Slatkine & Cie",
    groupe: "Indépendant (Genève)",
    ville: "Genève (Suisse)",
    genres: ["Littérature suisse", "Littérature française", "Essai", "Histoire"],
    specialite: "Maison genevoise de référence pour la francophonie. Ouverte aux auteurs suisses et français.",
    prestige: 2,
    voie: "email",
    contact: "edition@slatkine.com",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "1 à 2 pages",
      noteIntention: false,
      bio: true,
      extraits: true,
      extraitsNbPages: 30,
      formatManuscrit: "Fichier Word ou PDF",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "2 à 4 mois",
    conseil: "Un lien avec la Suisse ou la francophonie internationale est apprécié mais pas obligatoire.",
    noteExpert: "Bonne option pour des auteurs francophones hors France métropolitaine.",
  },
  {
    id: "serge-safran",
    nom: "Serge Safran Éditeur",
    groupe: "Indépendant",
    ville: "Paris",
    genres: ["Littérature exigeante", "Roman", "Essai", "Poésie"],
    specialite: "Petite maison indépendante au catalogue resserré et cohérent. Qualité absolue.",
    prestige: 2,
    voie: "courrier",
    contact: "32, rue du Plateau — 75019 Paris",
    exigences: {
      lettre: true,
      synopsis: true,
      synopsisLongueur: "1 page",
      noteIntention: true,
      noteIntentionLongueur: "1 page",
      bio: true,
      extraits: true,
      extraitsNbPages: 30,
      formatManuscrit: "Standard",
      longueurMin: null,
      longueurMax: null,
    },
    delaiReponse: "3 à 6 mois",
    conseil: "Très sélectif malgré sa taille. N'envoyez votre manuscrit que si votre texte est parfaitement abouti.",
    noteExpert: "Maison confidentielle mais reconnue par la critique littéraire. Accompagnement éditorial rare.",
  },
]

/** Retourne un éditeur par son id. */
export function getPublisherById(id) {
  return PUBLISHERS.find(p => p.id === id) ?? null
}

/** Labels pour la voie d'envoi */
export const VOIE_LABELS = {
  courrier: "📮 Courrier postal",
  email: "📧 Email",
  portail: "🌐 Portail en ligne",
  agent: "🤝 Via agent littéraire",
}

/** Retourne les étoiles de prestige sous forme de texte */
export function prestigeStars(n) {
  return "★".repeat(n) + "☆".repeat(5 - n)
}
