const conflits = [
  {
    id: 'rivalite',
    label: 'Rivalité',
    alias: ['rivalité', 'rivalite'],
    famille: 'conflits interpersonnels',
    definitionCourte: 'Affrontement entre deux personnes qui veulent la même place ou la même victoire.',
    natureDuConflit: 'opposition directe',
    forcesEnPresence: ['deux ambitions incompatibles', 'besoin de reconnaissance'],
    declencheursFrequents: ['mise en concurrence', 'comparaison publique'],
    formesVisibles: ['piques', 'défi ouvert'],
    formesCachees: ['surveillance', 'ressentiment'],
    penseesTypiques: ['Je ne vais pas le laisser gagner.'],
    comportementsTypiques: ['surenchérit', 'cherche à prendre l’avantage'],
    signauxRelationnels: ['tension immédiate', 'rapport de force latent'],
    escaladeTypique: ['compétition', 'hostilité', 'affrontement'],
    consequencesProbables: ['détérioration du lien', 'rupture'],
    voiesDAgravation: ['humiliation publique', 'injustice perçue'],
    voiesDeResolution: ['reconnaissance mutuelle', 'objectifs distincts'],
    contextesFavorables: ['travail', 'fratrie', 'sport'],
    personnagesSouventConcernes: ['ambitieux', 'orgueilleux'],
    notesEditoriales: ['La rivalité devient forte quand chacun a de vraies raisons de gagner.'],
  },
  {
    id: 'jalousie',
    label: 'Jalousie',
    alias: ['jalousie'],
    famille: 'conflits interpersonnels',
    definitionCourte: 'Conflit né de la peur de perdre une place affective ou symbolique au profit d’un autre.',
    natureDuConflit: 'menace ressentie sur un lien',
    forcesEnPresence: ['peur de remplacement', 'attachement possessif'],
    declencheursFrequents: ['proximité avec un tiers', 'attention déplacée'],
    formesVisibles: ['reproches', 'surveillance'],
    formesCachees: ['rumination', 'froideur'],
    penseesTypiques: ['Je vais perdre ma place.'],
    comportementsTypiques: ['teste la loyauté', 'compare'],
    signauxRelationnels: ['susceptibilité', 'besoin de réassurance'],
    escaladeTypique: ['inquiétude', 'soupçon', 'crise'],
    consequencesProbables: ['méfiance', 'rupture'],
    voiesDAgravation: ['ambiguïté', 'mensonge'],
    voiesDeResolution: ['clarification', 'réassurance crédible'],
    contextesFavorables: ['couple', 'fratrie', 'amitié fusionnelle'],
    personnagesSouventConcernes: ['insécures', 'possessifs'],
    notesEditoriales: ['La jalousie mêle souvent peur, amour et humiliation.'],
  },
  {
    id: 'trahison',
    label: 'Trahison',
    alias: ['trahison', 'trahir'],
    famille: 'conflits interpersonnels',
    definitionCourte: 'Brisure du lien provoquée par la violation d’une confiance ou d’une loyauté.',
    natureDuConflit: 'cassure morale et relationnelle',
    forcesEnPresence: ['confiance accordée', 'loyauté rompue'],
    declencheursFrequents: ['secret révélé', 'mensonge grave'],
    formesVisibles: ['confrontation directe', 'rupture immédiate'],
    formesCachees: ['sidération', 'vengeance différée'],
    penseesTypiques: ['Je ne pourrai plus lui faire confiance.'],
    comportementsTypiques: ['coupe le contact', 'cherche une explication'],
    signauxRelationnels: ['distance brutale', 'glaciation du lien'],
    escaladeTypique: ['découverte', 'choc', 'rupture ou vengeance'],
    consequencesProbables: ['rupture profonde', 'méfiance durable'],
    voiesDAgravation: ['déni', 'minimisation'],
    voiesDeResolution: ['aveu complet', 'réparation réelle'],
    contextesFavorables: ['couple', 'famille', 'amitié'],
    personnagesSouventConcernes: ['fidèles', 'protecteurs'],
    notesEditoriales: ['La trahison est d’autant plus forte que la confiance initiale était grande.'],
  },
  {
    id: 'humiliation',
    label: 'Humiliation',
    alias: ['humiliation'],
    famille: 'conflits interpersonnels',
    definitionCourte: 'Conflit provoqué par un rabaissement subi devant autrui ou ressenti comme tel.',
    natureDuConflit: 'atteinte à la dignité',
    forcesEnPresence: ['honte', 'blessure d’ego'],
    declencheursFrequents: ['moquerie publique', 'rabaissement verbal'],
    formesVisibles: ['silence figé', 'réponse sèche'],
    formesCachees: ['honte brûlante', 'désir de vengeance'],
    penseesTypiques: ['Tout le monde a vu.'],
    comportementsTypiques: ['se ferme', 'attaque en retour'],
    signauxRelationnels: ['hostilité froide', 'évitement du regard'],
    escaladeTypique: ['exposition', 'honte', 'vengeance ou rupture'],
    consequencesProbables: ['rancune', 'perte d’estime de soi'],
    voiesDAgravation: ['public nombreux', 'répétition'],
    voiesDeResolution: ['excuse claire', 'réparation publique'],
    contextesFavorables: ['école', 'travail', 'famille autoritaire'],
    personnagesSouventConcernes: ['fiers', 'ambitieux'],
    notesEditoriales: ['L’humiliation mêle honte, colère et mémoire durable.'],
  },
  {
    id: 'domination',
    label: 'Domination',
    alias: ['domination'],
    famille: 'conflits interpersonnels',
    definitionCourte: 'Conflit où l’un cherche à imposer durablement sa volonté ou son pouvoir à l’autre.',
    natureDuConflit: 'rapport vertical et contraignant',
    forcesEnPresence: ['asymétrie de pouvoir', 'contrôle', 'résistance'],
    declencheursFrequents: ['désobéissance', 'fragilité de l’autre', 'position hiérarchique'],
    formesVisibles: ['ordre sec', 'interruption', 'sanction'],
    formesCachees: ['culpabilisation', 'pression subtile', 'contrôle affectif'],
    penseesTypiques: ['Il doit rester à sa place.'],
    comportementsTypiques: ['impose le rythme', 'teste l’obéissance'],
    signauxRelationnels: ['déséquilibre constant', 'peur chez l’autre'],
    escaladeTypique: ['prise d’ascendant', 'contrôle accru', 'rupture ou soumission'],
    consequencesProbables: ['soumission', 'rébellion', 'destruction du lien'],
    voiesDAgravation: ['isolement', 'absence de contre-pouvoir'],
    voiesDeResolution: ['limites fermes', 'rééquilibrage du pouvoir', 'séparation'],
    contextesFavorables: ['famille toxique', 'couple sous emprise', 'travail hiérarchique'],
    personnagesSouventConcernes: ['autoritaires', 'contrôlants'],
    notesEditoriales: ['La domination est plus forte quand elle se voit dans les détails du quotidien.'],
  },
  {
    id: 'manipulation',
    label: 'Manipulation',
    alias: ['manipulation'],
    famille: 'conflits interpersonnels',
    definitionCourte: 'Conflit où l’un agit sur l’autre de manière indirecte pour obtenir un résultat sans affrontement franc.',
    natureDuConflit: 'contrôle indirect',
    forcesEnPresence: ['intention cachée', 'influence psychologique', 'déséquilibre d’information'],
    declencheursFrequents: ['peur du refus direct', 'volonté de garder l’avantage'],
    formesVisibles: ['discours orienté', 'culpabilisation', 'flatterie intéressée'],
    formesCachees: ['mensonge partiel', 'réécriture des faits', 'fabrication du doute'],
    penseesTypiques: ['Il faut l’amener à choisir ce que je veux.'],
    comportementsTypiques: ['tourne autour du sujet', 'appuie sur les failles'],
    signauxRelationnels: ['confusion', 'culpabilité diffuse', 'perte de repères'],
    escaladeTypique: ['influence légère', 'prise de terrain', 'emprise ou révélation'],
    consequencesProbables: ['perte de confiance', 'dépendance', 'rupture'],
    voiesDAgravation: ['isolement', 'secret', 'faible estime de soi chez la cible'],
    voiesDeResolution: ['mise au jour des mécanismes', 'retour aux faits', 'prise de distance'],
    contextesFavorables: ['couple', 'famille', 'travail', 'politique'],
    personnagesSouventConcernes: ['calculateurs', 'séducteurs', 'contrôlants'],
    notesEditoriales: ['La manipulation gagne en force quand le lecteur perçoit les signes avant la victime.'],
  },
];

export default conflits;
